name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/sample_app .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sample_app

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sample_app
            
            # Stop all containers using port (safe cleanup)
            sudo docker ps -q --filter "name=sample_app" | xargs -r sudo docker stop
            sudo docker ps -aq --filter "name=sample_app" | xargs -r sudo docker rm
            
            # Run fresh container
            sudo docker run -d -p 3001:3001 --name sample_app ${{ secrets.DOCKER_USERNAME }}/sample_app